name: econtrole

services:
  postgres:
    image: postgres:16-alpine
    container_name: econtrole-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: econtrole
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "619038"
    volumes:
      - econtrole_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: econtrole-redis
    ports:
      - "6381:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - econtrole_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  econtrole_pgdata:
  econtrole_redisdata: